### ISSUE TITLE
Example Code Missing directClient Variable

### ISSUE THREAD

**Issue by CValeron** [node-real/js-direct-route#12]
Hi,

could you please provide more and full examples ? Thank you very much

**Comment by LubomirKurpel** [comment]
This code works, basicly just replace "directClient" with "web3" and it should work. Docs for this project are very misleading indeed.

`
// Init client
const Web3 = require('@node-real/web3');

// var directRouteEndPoint = "https://api.nodereal.io/direct-route"; // MAINNET
var directRouteEndPoint = "https://testnet-api.nodereal.io/direct-route"; // TESTNET
let web3 = new Web3(directRouteEndPoint);

async function main() {
	
	const bundlePrice = await web3.eth.getBundlePrice();
	var price = bundlePrice.minimalGasPrice;
	if (price < bundlePrice.bundlePrice) {
		price = bundlePrice.bundlePrice;
	}
	
	console.log(price);

}

main()
.then(() => process.exit(0))
.catch((error) => {
    console.error(error);
    process.exit(1);
});`

**Comment by rashtug2** [comment]
am getting this error, can anyone help in setting this up please?


(node:357958) UnhandledPromiseRejectionWarning: Error: Invalid number of parameters for "deposit". Got 0 expected 2!
    at Object.InvalidNumberOfParams (/home/emperior/Videos/js-direct-route/node_modules/@node-real/web3-eth/node_modules/web3-core-helpers/lib/errors.js:33:16)
    at Object._createTxObject (/home/emperior/Videos/js-direct-route/node_modules/@node-real/web3-eth/node_modules/web3-eth-contract/lib/index.js:669:22)
    at sendBNBByBundleWithDepositCoinbaseDemo (/home/emperior/Videos/js-direct-route/bundle2.js:39:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:357958) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:357958) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{
  status: 0,
  validators: { MathWallet: 0, NodeReal: 0, 'TW Staking': 0 }
}
{ bundlePrice: 20000000000, minimalGasPrice: 20000000000 }
